### ISSUE TITLE
Why this repository is empty?

### ISSUE THREAD

**Issue by vaseline555** [youngandbin/--_----#1]
Dear Youngbin,

Why this repository is initialized with no contents?
Please clarify.

Thank you.

Best,
Adam

**Comment by youngandbin** [comment]
Dear Adam

WTF is this

Seriously,
Youngbin

**Comment by vaseline555** [comment]
How dare you saying 'WTF' to me? I am going to let your professor know of your use of abusive language.
Sugoring.


Best,
Adam

**Comment by youngandbin** [comment]
Adam,

My professor just said that it's totally okay.

WTF,
Youngbin
